controller_manager:
  ros__parameters:
    update_rate: 100

#    joint_state_controller:
#      type: joint_state_controller/JointStateController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controllers:
      type: effort_controllers/JointGroupEffortController

effort_controllers:
  ros__parameters:
    joints:
      - FL_HAA
      - FL_HFE
      - FL_KFE
#      - FL_ANKLE
      - FR_HAA
      - FR_HFE
      - FR_KFE
#      - FR_ANKLE
      - HL_HAA
      - HL_HFE
      - HL_KFE
#      - HL_ANKLE
      - HR_HAA
      - HR_HFE
      - HR_KFE
#      - HR_ANKLE
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort